# Broadcast master safety-net limiter capture side
context.modules = [
    {  name = libpipewire-module-filter-chain
        args = {
            node.description = "Broadcast master safety-net limiter capture side"
            audio.rate = 48000
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name = "hapax-broadcast-normalized-capture"
            }
            playback.props = {
                node.name = "hapax-broadcast-normalized-capture-playback"
            target.object = "hapax-broadcast-master"
            }
        }
    }
]
