# ZOOM LiveTrak L-12 multichannel USB capture
context.objects = [
    {  factory = adapter
        args = {
            factory.name = api.alsa.pcm.source
            node.name    = "alsa_input.usb-ZOOM_Corporation_L-12_8253FFFFFFFFFFFF9B5FFFFFFFFFFFFF-00.multichannel-input"
            media.class  = Audio/Source
            audio.format = S32LE
            audio.channels = 14
            audio.position = [ AUX0 AUX1 AUX2 AUX3 AUX4 AUX5 AUX6 AUX7 AUX8 AUX9 AUX10 AUX11 AUX12 AUX13 ]
            api.alsa.path = "hw:CARD=L12"
            api.alsa.use-acp = false
        }
    }
]
