# ZOOM LiveTrak L-12 USB return, FL/FR/RL/RR
context.objects = [
    {  factory = adapter
        args = {
            factory.name = api.alsa.pcm.sink
            node.name    = "alsa_output.usb-ZOOM_Corporation_L-12_8253FFFFFFFFFFFF9B5FFFFFFFFFFFFF-00.analog-surround-40"
            media.class  = Audio/Sink
            audio.format = S32LE
            audio.channels = 4
            audio.position = [ FL FR RL RR ]
            api.alsa.path = "surround40:CARD=L12"
        }
    }
]
