# M8 USB source capture side routed to M8 loudnorm
context.modules = [
    {  name = libpipewire-module-filter-chain
        args = {
            node.description = "M8 USB source capture side routed to M8 loudnorm"
            audio.rate = 48000
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name = "hapax-m8-instrument-capture"
            }
            playback.props = {
                node.name = "hapax-m8-instrument-capture-playback"
            target.object = "alsa_input.usb-Dirtywave_M8_16558390-02.analog-stereo"
            }
        }
    }
]
