# Dirtywave M8 USB audio source, optional hardware endpoint
context.objects = [
    {  factory = adapter
        args = {
            factory.name = api.alsa.pcm.source
            node.name    = "alsa_input.usb-Dirtywave_M8_16558390-02.analog-stereo"
            media.class  = Audio/Source
            audio.format = S32LE
            audio.channels = 2
            audio.position = [ FL FR ]
            api.alsa.path = "hw:M8,0"
        }
    }
]
