# Torso S-4 pro-audio multichannel input
context.objects = [
    {  factory = adapter
        args = {
            factory.name = api.alsa.pcm.source
            node.name    = "alsa_input.usb-Torso_Electronics_S-4_fedcba9876543220-03.multichannel-input"
            media.class  = Audio/Source
            audio.format = S32LE
            audio.channels = 10
            audio.position = [ AUX0 AUX1 AUX2 AUX3 AUX4 AUX5 AUX6 AUX7 AUX8 AUX9 ]
            api.alsa.path = "hw:CARD=S4"
        }
    }
]
