# TTS broadcast loopback capture side
context.modules = [
    {  name = libpipewire-module-filter-chain
        args = {
            node.description = "TTS broadcast loopback capture side"
            audio.rate = 48000
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name = "hapax-tts-broadcast-capture"
            }
            playback.props = {
                node.name = "hapax-tts-broadcast-capture-playback"
            target.object = "hapax-tts-duck"
            }
        }
    }
]
