# Blue Yeti headphone monitor, off-L-12 private endpoint
context.objects = [
    {  factory = adapter
        args = {
            factory.name = api.alsa.pcm.sink
            node.name    = "alsa_output.usb-Blue_Microphones_Yeti_Stereo_Microphone_REV8-00.analog-stereo"
            media.class  = Audio/Sink
            audio.format = S32LE
            audio.channels = 2
            audio.position = [ FL FR ]
            api.alsa.path = "front:CARD=Yeti"
        }
    }
]
