"""Tests for MidiClockBackend — mocked mido, tempo detection, transport state."""

from __future__ import annotations

import time
import unittest
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

from agents.hapax_daimonion.backends.midi_clock import _PPQN, MidiClockBackend
from agents.hapax_daimonion.primitives import Behavior
from agents.hapax_daimonion.timeline import TransportState


def _msg(msg_type: str) -> SimpleNamespace:
    """Create a minimal mido-like message."""
    return SimpleNamespace(type=msg_type)


class TestMidiClockBackend(unittest.TestCase):
    def _make_backend(self) -> MidiClockBackend:
        backend = MidiClockBackend(port_name="Test Port")
        # Manually set available since we won't actually open a port
        backend._available = True
        return backend

    def test_transport_state_machine(self):
        """STOPPED → start → PLAYING → stop → STOPPED → continue → PLAYING."""
        b = self._make_backend()
        self.assertEqual(b._transport, TransportState.STOPPED)

        b._on_message(_msg("start"))
        self.assertEqual(b._transport, TransportState.PLAYING)

        b._on_message(_msg("stop"))
        self.assertEqual(b._transport, TransportState.STOPPED)

        b._on_message(_msg("continue"))
        self.assertEqual(b._transport, TransportState.PLAYING)

    def test_tempo_detection_from_ticks(self):
        """Inject 24 clock ticks at known intervals → detect tempo."""
        b = self._make_backend()
        b._on_message(_msg("start"))

        # 120 BPM = 2 beats/sec = 48 ticks/sec → tick interval = 1/48 ≈ 0.020833s
        tick_interval = 60.0 / (120.0 * _PPQN)

        base_time = time.monotonic()
        for i in range(_PPQN + 1):
            t = base_time + i * tick_interval
            b._tick_times.append(t)
            if b._transport is TransportState.PLAYING:
                b._tick_count += 1
            b._update_tempo()

        # Tempo should be approximately 120 BPM
        self.assertAlmostEqual(b._tempo, 120.0, delta=1.0)

    def test_contribute_updates_behaviors(self):
        b = self._make_backend()
        b._on_message(_msg("start"))

        behaviors: dict[str, Behavior] = {}
        b.contribute(behaviors)

        self.assertIn("timeline_mapping", behaviors)
        self.assertIn("beat_position", behaviors)
        self.assertIn("bar_position", behaviors)
        self.assertIn("midi_clock_transport", behaviors)

    def test_contribute_transport_stopped(self):
        b = self._make_backend()
        behaviors: dict[str, Behavior] = {}
        b.contribute(behaviors)

        mapping = behaviors["timeline_mapping"].value
        self.assertEqual(mapping.transport, TransportState.STOPPED)
        self.assertEqual(behaviors["midi_clock_transport"].value, "STOPPED")

    def test_contribute_transport_playing_publishes_enum_name(self):
        """midi_clock_transport behavior carries TransportState enum *name* (PLAYING)."""
        b = self._make_backend()
        b._on_message(_msg("start"))

        behaviors: dict[str, Behavior] = {}
        b.contribute(behaviors)

        self.assertEqual(behaviors["midi_clock_transport"].value, "PLAYING")

    def test_provides_includes_midi_clock_transport(self):
        """provides set includes midi_clock_transport so registration discovers it."""
        b = self._make_backend()
        self.assertIn("midi_clock_transport", b.provides)

    def test_beat_position_monotonic_during_playing(self):
        """beat_position should be monotonically non-decreasing during PLAYING."""
        b = self._make_backend()
        b._on_message(_msg("start"))

        positions = []
        for i in range(10):
            # Simulate time passing with ticks
            b._tick_count = i * 6  # 6 ticks per sample
            behaviors: dict[str, Behavior] = {}
            b.contribute(behaviors)
            positions.append(behaviors["beat_position"].value)

        for i in range(1, len(positions)):
            self.assertGreaterEqual(positions[i], positions[i - 1])

    @patch("agents.hapax_daimonion.backends.midi_clock.mido", create=True)
    def test_start_opens_port(self, mock_mido):
        b = MidiClockBackend(port_name="Test Port")
        b.start()
        # Multi-port refactor 2026-05-02: callback is a per-port closure
        # generated by _make_callback, not b._on_message directly. Verify
        # open_input was called once with the correct port name + callback kwarg.
        mock_mido.open_input.assert_called_once()
        call = mock_mido.open_input.call_args
        assert call.args[0] == "Test Port"
        assert "callback" in call.kwargs
        self.assertTrue(b._available)

    @patch("agents.hapax_daimonion.backends.midi_clock.mido", create=True)
    def test_start_unavailable_port(self, mock_mido):
        mock_mido.open_input.side_effect = OSError("No such port")
        b = MidiClockBackend(port_name="Missing Port")
        b.start()
        self.assertFalse(b._available)

    def test_stop_cleans_up(self):
        b = self._make_backend()
        mock_port = MagicMock()
        # Multi-port refactor 2026-05-02: _port → _ports (list).
        b._ports = [mock_port]
        b._available = True
        b.stop()
        mock_port.close.assert_called_once()
        self.assertFalse(b._available)
        self.assertEqual(b._ports, [])

    def test_tick_count_reset_on_start(self):
        b = self._make_backend()
        b._tick_count = 100
        b._on_message(_msg("start"))
        self.assertEqual(b._tick_count, 0)

    def test_bar_position(self):
        b = self._make_backend()
        b._on_message(_msg("start"))
        b._tick_count = _PPQN * 8  # 8 beats = 2 bars at 4/4
        behaviors: dict[str, Behavior] = {}
        b.contribute(behaviors)
        self.assertAlmostEqual(behaviors["bar_position"].value, 2.0, delta=0.1)


if __name__ == "__main__":
    unittest.main()


class TestMidiClockBackendMultiPort(unittest.TestCase):
    """Multi-port arbitration tests (m8-midi-clock-peer-tempo-source)."""

    @patch("agents.hapax_daimonion.backends.midi_clock.mido", create=True)
    def test_two_ports_both_open(self, mock_mido):
        """Two configured ports each get an open_input call."""
        b = MidiClockBackend(port_names=["OXI One", "M8 MIDI 1"])
        b.start()
        self.assertEqual(mock_mido.open_input.call_count, 2)
        called_ports = [c.args[0] for c in mock_mido.open_input.call_args_list]
        self.assertIn("OXI One", called_ports)
        self.assertIn("M8 MIDI 1", called_ports)
        self.assertTrue(b._available)

    @patch("agents.hapax_daimonion.backends.midi_clock.mido", create=True)
    def test_alt_port_absent_falls_back_to_primary(self, mock_mido):
        """If alt port fails to open, backend stays available with primary."""

        def open_input(name, callback=None):
            if name == "M8 MIDI 1":
                raise OSError("M8 not enumerated")
            return MagicMock()

        mock_mido.open_input.side_effect = open_input
        b = MidiClockBackend(port_names=["OXI One", "M8 MIDI 1"])
        b.start()
        self.assertTrue(b._available)  # OXI opened; backend available
        self.assertEqual(len(b._ports), 1)  # only OXI port held

    @patch("agents.hapax_daimonion.backends.midi_clock.mido", create=True)
    def test_both_ports_absent_backend_unavailable(self, mock_mido):
        """If all ports fail, backend is unavailable but does not raise."""
        mock_mido.open_input.side_effect = OSError("nope")
        b = MidiClockBackend(port_names=["OXI One", "M8 MIDI 1"])
        b.start()  # must not raise
        self.assertFalse(b._available)

    def test_transport_message_promotes_source_port(self):
        """A start message from any port promotes that port to active."""
        b = MidiClockBackend(port_names=["OXI One", "M8 MIDI 1"])
        # Send start from M8
        b._on_message(_msg("start"), source_port="M8 MIDI 1")
        self.assertEqual(b._active_port, "M8 MIDI 1")
        self.assertEqual(b._transport, TransportState.PLAYING)

    def test_clock_from_non_winner_ignored_during_play(self):
        """When OXI is PLAYING, clock ticks from M8 don't add to tick_count."""
        b = MidiClockBackend(port_names=["OXI One", "M8 MIDI 1"])
        # OXI starts playing
        b._on_message(_msg("start"), source_port="OXI One")
        self.assertEqual(b._active_port, "OXI One")
        # OXI sends 5 clock ticks
        for _ in range(5):
            b._on_message(_msg("clock"), source_port="OXI One")
        oxi_tick_count = b._tick_count
        # M8 sends a clock tick — should be IGNORED (OXI is winning)
        b._on_message(_msg("clock"), source_port="M8 MIDI 1")
        self.assertEqual(b._tick_count, oxi_tick_count)  # unchanged

    def test_m8_transport_promotes_then_takes_over(self):
        """If M8 sends start while OXI is playing, M8 wins."""
        b = MidiClockBackend(port_names=["OXI One", "M8 MIDI 1"])
        b._on_message(_msg("start"), source_port="OXI One")
        b._on_message(_msg("start"), source_port="M8 MIDI 1")
        self.assertEqual(b._active_port, "M8 MIDI 1")
        self.assertEqual(b._transport, TransportState.PLAYING)
        # Now M8 clocks count
        b._on_message(_msg("clock"), source_port="M8 MIDI 1")
        self.assertEqual(b._tick_count, 1)
