"""``compile_descriptor()`` — pure compiler from AudioGraph to artefacts.

Implements spec §3. Pure function, no side-effects. The daemon's
``apply()`` is the only thing that turns :class:`CompiledArtefacts`
into filesystem mutations and pactl invocations.

Phase 1 ships the compiler signature + invariant integration + probe
generation. The conf-emit step delegates to the existing
``shared.audio_topology_generator`` for ``generate_confs`` parity, and
the wireplumber emit step is the new capability surfaced by gap G-12.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from shared.audio_graph.invariants import (
    InvariantSeverity,
    InvariantViolation,
    check_all_invariants,
)
from shared.audio_graph.schema import (
    AudioGraph,
    LoopbackTopology,
)

# ---------------------------------------------------------------------------
# Output dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PactlLoad:
    """Idempotent ``pactl load-module module-loopback ...`` invocation.

    Pattern matches ``~/.local/bin/hapax-obs-monitor-load``:

      1. wait_for_sink(target_sink, timeout_s=60)
      2. find_existing_module_id(source, sink) → if present, no-op
      3. pactl load-module module-loopback ...
      4. verify the new module's bound source/sink match the request
    """

    source: str
    sink: str
    source_dont_move: bool = True
    sink_dont_move: bool = True
    latency_msec: int = 20
    expected_source_port_pattern: str | None = None
    expected_sink_port_pattern: str | None = None
    description: str = ""


@dataclass(frozen=True)
class PostApplyProbe:
    """A signal-flow probe that runs after apply.

    Reuses the existing ``agents.broadcast_audio_health_producer``
    inject + capture pattern (17.5 kHz tone + FFT detection) but
    binds one probe per CRITICAL boundary in the descriptor.

    The egress probe ALSO carries the continuous-RMS / crest gate
    used by the daemon's circuit breaker once P5 ships. For P1 these
    are descriptive; the daemon implements them in P5.
    """

    name: str
    sink_to_inject: str
    source_to_capture: str
    inject_channels: int
    expected_outcome: Literal["detected", "not_detected"]
    egress_rms_band_dbfs: tuple[float, float] | None = None
    egress_max_crest: float | None = None


@dataclass(frozen=True)
class CompiledArtefacts:
    """Complete output of ``compile_descriptor()``.

    The daemon's ``apply()`` consumes this and turns it into atomic
    filesystem writes + pactl invocations + post-apply probes.
    """

    pipewire_confs: dict[str, str] = field(default_factory=dict)
    wireplumber_confs: dict[str, str] = field(default_factory=dict)
    pactl_loads: list[PactlLoad] = field(default_factory=list)
    pre_apply_violations: list[InvariantViolation] = field(default_factory=list)
    post_apply_probes: list[PostApplyProbe] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Conf emission
# ---------------------------------------------------------------------------


def _emit_pipewire_confs(graph: AudioGraph) -> dict[str, str]:
    """Emit one PipeWire conf per node in the graph.

    P1 ships a deterministic stub generator that emits a conf-shaped
    string for each filter-chain / loopback / tap node. P4 will
    replace this by delegating to the existing
    ``shared.audio_topology_generator.generate_confs`` once the
    AudioGraph → TopologyDescriptor adapter lands.
    """
    out: dict[str, str] = {}
    for node in graph.nodes:
        # Skip ALSA hardware endpoints — those are kernel-managed.
        if node.kind.value in {"alsa_source", "alsa_sink"}:
            continue
        path = f"{node.pipewire_name}.conf"
        # Deterministic, sorted, comment-headered shape.
        body = (
            f"# Generated by shared.audio_graph.compiler — DO NOT HAND-EDIT\n"
            f"# Node: {node.id} (kind={node.kind.value})\n"
            f"# Description: {node.description or '(no description)'}\n"
            f"# Channel count: {node.channels.count}\n"
            f"# Channel positions: {' '.join(node.channels.positions)}\n"
        )
        if node.target_object:
            body += f"# target.object: {node.target_object}\n"
        if node.fail_closed:
            body += "# fail_closed: true\n"
        if node.format:
            body += (
                f"# format: rate={node.format.rate_hz} "
                f"sample={node.format.format} channels={node.format.channels}\n"
            )
        if node.filter_chain_template:
            body += f"# filter_chain_template: {node.filter_chain_template.value}\n"
        out[path] = body
    return out


def _emit_wireplumber_confs(graph: AudioGraph) -> dict[str, str]:
    """Emit WirePlumber confs from typed rules + role-loopback infrastructure.

    Gap G-12 / G-13: surfaces the typed shape so the daemon can write
    deterministic WirePlumber confs derived from the AudioGraph.

    P1 emits stub headers with the typed parameters; P4 will replace
    this with the actual WirePlumber conf templates (matching the
    operator-edited examples currently under
    ``~/.config/wireplumber/wireplumber.conf.d/``).
    """
    out: dict[str, str] = {}
    # Role-based loopback infrastructure (gap G-13).
    for idx, sink in enumerate(graph.media_role_sinks):
        path = f"50-media-role-sinks-{idx}.conf"
        body = "# Generated by shared.audio_graph.compiler — DO NOT HAND-EDIT\n"
        body += (
            f"# duck_level={sink.duck_policy.duck_level} "
            f"default_media_role={sink.duck_policy.default_media_role}\n"
        )
        for lb in sink.loopbacks:
            body += (
                f"# Role: {lb.role} "
                f"node={lb.loopback_node_name} "
                f"priority={lb.priority} "
                f"preferred_target={lb.preferred_target}\n"
            )
        out[path] = body
    # ALSA card profile pins (gaps G-2 + G-17).
    for pin in graph.alsa_profile_pins:
        path = f"60-alsa-profile-{pin.card_match.replace('*', '_').replace('~', '_')}.conf"
        body = "# Generated — ALSA card profile pin\n"
        body += f"# match: {pin.card_match}\n"
        if pin.profile:
            body += f"# device.profile: {pin.profile}\n"
        if pin.api_alsa_use_acp is not None:
            body += f"# api.alsa.use-acp: {pin.api_alsa_use_acp}\n"
        out[path] = body
    # Bluez rules (gap G-14).
    for idx, rule in enumerate(graph.bluez_rules):
        out[f"56-bluez-{idx}.conf"] = f"# Generated — bluez rule\n# {rule.description}\n"
    # Stream-restore rules (gap G-15).
    for idx, rule in enumerate(graph.stream_restore_rules):
        out[f"55-stream-restore-{idx}.conf"] = (
            f"# Generated — stream-restore rule\n"
            f"# state.restore-target={rule.state_restore_target} "
            f"state.restore-props={rule.state_restore_props}\n"
        )
    # Stream pins (gap G-16).
    for idx, pin in enumerate(graph.stream_pins):
        out[f"56-stream-pin-{idx}.conf"] = (
            f"# Generated — stream pin\n# target.object={pin.target_object}\n"
        )
    # Untyped wireplumber rules (gap G-12 catch-all).
    for rule in graph.untyped_wireplumber_rules:
        out[rule.name] = rule.raw_content
    return out


def _emit_pactl_loads(graph: AudioGraph) -> list[PactlLoad]:
    """Emit a PactlLoad for each LoopbackTopology with apply_via_pactl_load=True.

    Pattern lifted from ``~/.local/bin/hapax-obs-monitor-load`` and
    its sister ``hapax-livestream-tap-load``.
    """
    out: list[PactlLoad] = []
    for lb in graph.loopbacks:
        if not lb.apply_via_pactl_load:
            continue
        out.append(
            PactlLoad(
                source=lb.source,
                sink=lb.sink,
                source_dont_move=lb.source_dont_move,
                sink_dont_move=lb.sink_dont_move,
                latency_msec=lb.latency_msec or 20,
                description=f"loopback {lb.node_id}",
            )
        )
    return out


def _build_post_apply_probes(graph: AudioGraph) -> list[PostApplyProbe]:
    """One probe per egress + every private/broadcast crossing + every downmix.

    Egress probe drives the §4.2 circuit breaker (P5). Private/broadcast
    crossing probes assert silence on broadcast. Channel-count change
    probes assert flow after downmix (catch silent-downmix class —
    today's failure #5).
    """
    probes: list[PostApplyProbe] = []
    # Egress probe — the breaker target. Accept either canonical id
    # (``obs-broadcast-remap``) or the live pipewire_name form
    # (``hapax-obs-broadcast-remap``).
    if any(n.id in {"obs-broadcast-remap", "hapax-obs-broadcast-remap"} for n in graph.nodes):
        probes.append(
            PostApplyProbe(
                name="obs-egress-band",
                sink_to_inject="hapax-livestream-tap",
                source_to_capture="hapax-obs-broadcast-remap.monitor",
                inject_channels=2,
                expected_outcome="detected",
                egress_rms_band_dbfs=(-40.0, -10.0),
                egress_max_crest=5.0,
            )
        )
    # Channel-count change probes.
    for cdm in graph.channel_downmixes:
        try:
            tgt = graph.node_by_id(cdm.target_node)
        except KeyError:
            continue
        probes.append(
            PostApplyProbe(
                name=f"downmix-{cdm.source_node}-to-{cdm.target_node}",
                sink_to_inject=cdm.source_node,
                source_to_capture=f"{tgt.pipewire_name}.monitor",
                inject_channels=2,
                expected_outcome="detected",
            )
        )
    # Private endpoint silence probes.
    for node in graph.nodes:
        if node.private_monitor_endpoint or node.fail_closed:
            probes.append(
                PostApplyProbe(
                    name=f"private-{node.id}-leak-check",
                    sink_to_inject=node.id,
                    source_to_capture="hapax-obs-broadcast-remap.monitor",
                    inject_channels=2,
                    expected_outcome="not_detected",
                )
            )
    return probes


# ---------------------------------------------------------------------------
# Public entry-point
# ---------------------------------------------------------------------------


def compile_descriptor(graph: AudioGraph) -> CompiledArtefacts:
    """Compile an AudioGraph into deployable artefacts.

    Pure function. No side-effects. If the descriptor has any
    BLOCKING invariant violations, returns an empty CompiledArtefacts
    with the violations populated (the daemon refuses the apply).

    Determinism: the same descriptor produces byte-identical
    artefacts across runs. We do not include any timestamps in the
    output — the daemon is the only thing that tags the apply with a
    timestamp at the snapshot directory level.
    """
    violations = check_all_invariants(graph)
    blocking = [v for v in violations if v.severity == InvariantSeverity.BLOCKING]
    if blocking:
        return CompiledArtefacts(
            pipewire_confs={},
            wireplumber_confs={},
            pactl_loads=[],
            pre_apply_violations=violations,
            post_apply_probes=[],
        )
    return CompiledArtefacts(
        pipewire_confs=_emit_pipewire_confs(graph),
        wireplumber_confs=_emit_wireplumber_confs(graph),
        pactl_loads=_emit_pactl_loads(graph),
        pre_apply_violations=violations,  # may include WARNING entries
        post_apply_probes=_build_post_apply_probes(graph),
    )


def loopbacks_apply_via_pactl(graph: AudioGraph) -> list[LoopbackTopology]:
    """Helper: return loopbacks the compiler will emit as PactlLoad."""
    return [lb for lb in graph.loopbacks if lb.apply_via_pactl_load]


__all__ = [
    "CompiledArtefacts",
    "PactlLoad",
    "PostApplyProbe",
    "compile_descriptor",
    "loopbacks_apply_via_pactl",
]
