# Hapax USB reliability override.
#
# Keep this later than distribution-provided uvcvideo snippets that may set
# quirks=0 and defeat the Hapax reliability baseline. usbcore may be built-in
# on this host; config/kernel-cmdline/hapax-usb-reliability.params is still the
# reboot-authoritative source for usbcore.usbfs_memory_mb=128.

options usbcore usbfs_memory_mb=128
options uvcvideo quirks=0x100 nodrop=0 timeout=5000
options snd-usb-audio implicit_fb=1
options snd-usb-audio quirk_flags=0x1686:0x03d5:0x40,0x1686:0x089e:0x40,0x1686:0x089f:0x40
