"""Health check modules. Importing this package registers all check groups."""

from . import (  # noqa: F401
    apperception,
    audio,
    auth,
    axioms,
    axioms_ef,
    backup,
    budget,
    capacity,
    connectivity,
    credentials,
    disk,
    docker,
    edge,
    endpoints,
    exploration,
    gpu,
    latency,
    m8_firmware,
    memory,
    models_ollama,
    profiles,
    qdrant,
    queues,
    secrets,
    skills,
    sync,
    systemd,
    traces,
    voice,
)
