#!/usr/bin/env python3
"""Generate `_manifest.yaml` and `_NOTICES.md` for the aesthetic library.

Scans `assets/aesthetic-library/` for asset files, builds manifest entries
by reading the per-source `provenance.yaml`, hashes each file with SHA-256,
and writes both output files. Intended to run at ingest time and whenever
new assets are added.

Usage:
    uv run python scripts/generate-aesthetic-manifest.py
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
LIB_ROOT = REPO_ROOT / "assets" / "aesthetic-library"


ASSET_KIND_MAP: dict[tuple[str, str], str] = {
    ("bitchx/splash", "banner.txt"): "splash",
    ("bitchx/quotes", "bitchx-quit.txt"): "quotes",
    ("bitchx/colors", "mirc16.yaml"): "palette",
    ("fonts", "Px437_IBM_VGA_8x16.ttf"): "font",
    ("fonts", "Px437_IBM_VGA_8x16.woff2"): "font",
}

# (source, kind, name) → relative path under LIB_ROOT
ASSET_NAME_MAP: dict[tuple[str, str, str], str] = {
    ("bitchx", "splash", "banner"): "bitchx/splash/banner.txt",
    ("bitchx", "quotes", "quit"): "bitchx/quotes/bitchx-quit.txt",
    ("bitchx", "palette", "mirc16"): "bitchx/colors/mirc16.yaml",
    ("fonts", "font", "px437"): "fonts/Px437_IBM_VGA_8x16.ttf",
    ("fonts", "font", "px437-woff2"): "fonts/Px437_IBM_VGA_8x16.woff2",
}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _provenance_for(source: str) -> dict:
    path = LIB_ROOT / source / "provenance.yaml"
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def build_manifest() -> dict:
    assets = []
    for (source, kind, name), rel in ASSET_NAME_MAP.items():
        asset_path = LIB_ROOT / rel
        if not asset_path.is_file():
            print(f"MISSING: {rel}", file=sys.stderr)
            sys.exit(1)
        prov = _provenance_for(source)
        assets.append(
            {
                "source": source,
                "kind": kind,
                "name": name,
                "path": rel,
                "sha256": _sha256(asset_path),
                "license": prov["license"],
                "author": prov["original_author"],
                "source_url": prov["source_url"],
                "extracted_date": str(prov["extracted_date"])[:10],
            }
        )
    return {"assets": assets}


def build_notices(manifest: dict) -> str:
    # Group by license for readability.
    by_license: dict[str, list[dict]] = {}
    for entry in manifest["assets"]:
        by_license.setdefault(entry["license"], []).append(entry)

    lines: list[str] = [
        "# NOTICES — aesthetic-library attributions",
        "",
        "Autogenerated by `scripts/generate-aesthetic-manifest.py`. Do not hand-edit.",
        "",
        "Every asset under `assets/aesthetic-library/` is third-party content",
        "redistributed under its declared license. This file is the canonical",
        "attribution surface; the omg.lol /credits page (ytb-OMG-CREDITS) and",
        "the in-stream credits ward consume it directly.",
        "",
    ]
    for license_key in sorted(by_license.keys()):
        lines.append(f"## {license_key}")
        lines.append("")
        # Collect unique (author, source_url) pairs within this license
        seen: set[tuple[str, str]] = set()
        entries = by_license[license_key]
        for entry in entries:
            key = (entry["author"], entry["source_url"])
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"- **{entry['author']}** — {entry['source_url']}")
        lines.append("")
        lines.append("Assets under this license:")
        lines.append("")
        for entry in entries:
            lines.append(
                f"- `{entry['path']}` "
                f"(source: `{entry['source']}`, kind: `{entry['kind']}`, "
                f"name: `{entry['name']}`)"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify current _manifest.yaml matches on-disk state (no write)",
    )
    args = parser.parse_args()

    manifest = build_manifest()
    notices = build_notices(manifest)
    manifest_yaml = yaml.safe_dump(manifest, sort_keys=False)

    mpath = LIB_ROOT / "_manifest.yaml"
    npath = LIB_ROOT / "_NOTICES.md"

    if args.check:
        current_manifest = mpath.read_text(encoding="utf-8") if mpath.exists() else ""
        current_notices = npath.read_text(encoding="utf-8") if npath.exists() else ""
        if current_manifest != manifest_yaml or current_notices != notices:
            print(
                "DRIFT: _manifest.yaml or _NOTICES.md is out of sync with on-disk "
                "assets. Re-run without --check to regenerate.",
                file=sys.stderr,
            )
            return 1
        print("OK: _manifest.yaml and _NOTICES.md are current.")
        return 0

    mpath.write_text(manifest_yaml, encoding="utf-8")
    npath.write_text(notices, encoding="utf-8")
    print(f"wrote {mpath.relative_to(REPO_ROOT)}")
    print(f"wrote {npath.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
