monitor.v4l2.rules = [
  {
    matches = [
      {
        node.name = "~v4l2_input.*"
        # Match all our loopback devices by device name
        api.v4l2.cap.driver = "v4l2 loopback"
      }
    ]
    actions = {
      update-props = {
        # Ensure they are available as camera portals in WebRTC/Chrome
        node.role = "Camera"
      }
    }
  }
]
